CONSOLE_LOG_LEVEL: WARNING
FILE_LOG_LEVEL: INFO
QUEUE_CONNECTION: amqp://guest:guest@queue/
CORE_BASE_URL: http://core:11434
MODEL_ID: deepseek-r1:14b  # qwen3:14b
MODEL_TEMPERATURE: 0.3
MODEL_NUM_PREDICT: 512
MODEL_TOP_P: 0.7