CONSOLE_LOG_LEVEL: DEBUG
FILE_LOG_LEVEL: DEBUG
QUEUE_CONNECTION: amqp://guest:guest@localhost/
CORE_BASE_URL: http://192.168.0.13:11434
MODEL_ID: llama3.1:8b-instruct-q8_0  # qwen3:14b,deepseek-r1:14b
MODEL_MULTIMODAL_ID: qwen2.5vl:7b
MODEL_TEMPERATURE: 0.3
MODEL_NUM_PREDICT: 4096
MODEL_NUM_CTX: 16384
MODEL_TOP_P: 0.7