CONSOLE_LOG_LEVEL: DEBUG
FILE_LOG_LEVEL: DEBUG
QUEUE_CONNECTION: amqp://guest:guest@localhost/
CORE_BASE_URL: http://192.168.0.13:11434
MODEL_ID: deepseek-r1:14b  # qwen3:14b
MODEL_TEMPERATURE: 0.3
MODEL_NUM_PREDICT: 512
MODEL_TOP_P: 0.7