CONSOLE_LOG_LEVEL: INFO
FILE_LOG_LEVEL: INFO
QUEUE_CONNECTION: amqp://guest:guest@queue/
DB_CONNECTION: sqlite:////approot/data/database/db.sql
DB_DIR: /approot/data/database
AIHIVE_ADDR: https://api.aihive.ir  # webhook base address