services:
  queue:
    image: rabbitmq:4.0.6-management
    ports:
      - ${PORT_RABBITMQ_MANAGEMENT}:15672
    volumes:
      - ../../../Outputs/IDCardOCR/rabbitmq_logs:/var/log/rabbitmq
      - ../../../Outputs/IDCardOCR/rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - TZ=Asia/Tehran
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log
    restart: always
    networks:
      robinnet: null

  engine:
    build:
      context: ./engine
      dockerfile: ./Dockerfile
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL}
        PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX_URL}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
        PIP_TIMEOUT: 500
        PIP_DISABLE_PIP_VERSION_CHECK: 1
        PIP_NO_CACHE_DIR: 1
        PIP_NO_BINARY: ":all:"
    command: bash ./cmd.sh
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./engine:/approot/src
      - ../../../Models/NcToTxt:/approot/models
      - ../../../Outputs/IDCardOCR:/approot/data
    environment:
      - TZ=Asia/Tehran
      - MPLCONFIGDIR=/tmp/matplotlib
      - MODE
    user: ${CUID}
    restart: always
    depends_on:
      - queue
    image: robin-nctotxt-engine:0.0.2
    networks:
      robinnet: null

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL}
        PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX_URL}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
        PIP_TIMEOUT: 500
    command: bash ./cmd.sh
    ports:
      - ${PORT_BACKEND}:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backend:/approot/src
      - ../../../Outputs/IDCardOCR:/approot/data
    environment:
      - TZ=Asia/Tehran
      - MODE
    user: ${CUID}
    restart: always
    depends_on:
      - queue
      - engine
    image: robin-nctotxt-backend:0.0.2
    networks:
      robinnet: null

networks:
  robinnet:
    driver: bridge