CONSOLE_LOG_LEVEL: INFO
FILE_LOG_LEVEL: INFO
QUEUE_CONNECTION: amqp://guest:guest@queue/
DB_CONNECTION: sqlite:///../../Outputs/database/db.sql
DB_DIR: ../../Outputs/database
AIHIVE_ADDR: https://api.aihive.ir  # webhook base address
BASE_URL_FILE_LINK: http://localhost:8005  # current service base address