CONSOLE_LOG_LEVEL: WARNING
FILE_LOG_LEVEL: INFO
QUEUE_CONNECTION: amqp://guest:guest@queue/
MODEL_IDs: SLPL/Sharif-wav2vec2,speechbrain/asr-whisper-medium-commonvoice-ar,jonatasgrosman/wav2vec2-large-xlsr-53-english