CONSOLE_LOG_LEVEL: DEBUG
FILE_LOG_LEVEL: DEBUG
QUEUE_CONNECTION: amqp://guest:guest@localhost/
MODEL_IDs: Sharif-wav2vec2,jonatasgrosman/wav2vec2-large-xlsr-53-arabic,jonatasgrosman/wav2vec2-large-xlsr-53-english