CONSOLE_LOG_LEVEL: DEBUG
FILE_LOG_LEVEL: DEBUG
QUEUE_CONNECTION: amqp://guest:guest@localhost/
MODEL_IDs: SLPL/Sharif-wav2vec2,speechbrain/asr-whisper-medium-commonvoice-ar,jonatasgrosman/wav2vec2-large-xlsr-53-english