CONSOLE_LOG_LEVEL: INFO
FILE_LOG_LEVEL: INFO
QUEUE_CONNECTION: amqp://guest:guest@localhost/
DB_CONNECTION: sqlite:///../../Outputs/database/db.sql
DB_DIR: ../../Outputs/database
AIHIVE_ADDR: http://api.robin-co.com  # webhook base address
BASE_URL_FILE_LINK: http://localhost:9000  # current service