version: '3.7'
services:
  queue:
    image: rabbitmq:4.0.6-management
    ports:
      - ${PORT_RABBIT_MANAGEMENT}:15672
    volumes:
      - ../Outputs/rabbitmq_logs:/var/log/rabbitmq
      - ../Outputs/rabbitmq_data:/var/lib/rabbitmq
      - ./src/rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - TZ=Asia/Tehran
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf  # Use the custom config file
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log  # Log file location
    restart: always
    networks:
      robinnet: null
  engine:
    build:
      context: ./src/engine
      dockerfile: ./Dockerfile-gpu
      args:
        - PIP_INDEX_URL
        - PIP_EXTRA_INDEX_URL
        - PIP_TRUSTED_HOST
        - PIP_TIMEOUT=500
    command: bash ./cmd.sh
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src/engine:/approot/src
      - ../Models:/approot/models
      - ../Outputs:/approot/data
    environment:
      - TZ=Asia/Tehran
      - MPLCONFIGDIR=/tmp/matplotlib
      - MODE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 1 # alternatively, use `count: all` for all GPUs
              device_ids: ['0']
              capabilities: [gpu]
    user: ${CUID}
    restart: always
    depends_on:
      - queue
    image: robin-asr-engine-gpu:0.0.1
    networks:
      robinnet: null
  backend:
    build:
      context: ./src/backend
      dockerfile: ./Dockerfile
      args:
        - PIP_INDEX_URL
        - PIP_EXTRA_INDEX_URL
        - PIP_TRUSTED_HOST
        - PIP_TIMEOUT=500
    command: bash ./cmd.sh
    ports:
      - ${PORT_BACKEND}:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src/backend:/approot/src
      - ../Outputs:/approot/data
    environment:
      - TZ=Asia/Tehran
      - MODE
    user: ${CUID}
    restart: always
    depends_on:
      - queue
      - engine
    image: robin-asr-backend:0.0.3
    networks:
      robinnet: null    
networks:
  robinnet:
    driver: bridge