services:
  queue:
    image: rabbitmq:4.0.6-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ../Outputs/rabbitmq_logs:/var/log/rabbitmq
      - ../Outputs/rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - TZ=Asia/Tehran
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log
    restart: always
    networks:
      robinnet: null

  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL}
        PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX_URL}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
        PIP_TIMEOUT: 500
        PIP_DISABLE_PIP_VERSION_CHECK: 1
        PIP_NO_CACHE_DIR: 1
        PIP_NO_BINARY: ":all:"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./engine:/approot/Final
      - ../Models:/approot/models
      - ../Outputs:/approot/data
    environment:
      - TZ=Asia/Tehran
      - MPLCONFIGDIR=/tmp/matplotlib
      - MODE=${MODE:-production}
    restart: always
    depends_on:
      - queue
    networks:
      robinnet: null

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL}
        PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX_URL}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
        PIP_TIMEOUT: 500

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backend:/app/backend
      - ../Outputs:/approot/data
    environment:
      - TZ=Asia/Tehran
      - MODE=${MODE:-production}
    restart: always
    depends_on:
      - queue
      - engine
    networks:
      robinnet: null
      
networks:
  robinnet:
    driver: bridge